apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: gcr.io/order-processing-microservice/order-api
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: order-env
