apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-worker
  template:
    metadata:
      labels:
        app: order-worker
    spec:
      containers:
        - name: order-worker
          image: gcr.io/order-processing-microservice/order-worker
          envFrom:
            - configMapRef:
                name: order-env
